package com.running.strava.domain

import java.time.ZonedDateTime

data class Activity(
    val id: Long,
    val name: String,
    val distance: Float,
    val movingTime: Int,
    val elapsedTime: Int,
    val totalElevationGain: Float,
    val type: String,
    val sportType: String?,
    val startDate: ZonedDateTime,
    val timezone: String,
    val averageSpeed: Float,
    val maxSpeed: Float,
    val averageHeartrate: Float?,
    val maxHeartrate: Float?,
    val averageCadence: Float?,
    val averageWatts: Float?,
    val maxWatts: Float?,
    val weightedAverageWatts: Int?,
    val kilojoules: Float?,
    val deviceWatts: Boolean?,
    val description: String?,
    val calories: Float?,
    val sufferScore: Int?,
    val hasHeartrate: Boolean,
    val elevHigh: Float?,
    val elevLow: Float?,
    val gearId: String?,
    val startLatlng: List<Double>?,
    val endLatlng: List<Double>?,
    val isTrainer: Boolean,
    val isCommute: Boolean,
    val isManual: Boolean,
    val isFlagged: Boolean,
    val workoutType: Int?,
    val originalStartDate: ZonedDateTime?,
    val laps: List<Lap>?,
    val splits: List<Split>?,
    val bestEfforts: List<BestEffort>?,
)

data class Lap(
    val id: Long,
    val name: String?,
    val elapsedTime: Int,
    val movingTime: Int,
    val startDate: ZonedDateTime,
    val startIndex: Int,
    val endIndex: Int,
    val distance: Float,
    val averageSpeed: Float,
    val maxSpeed: Float,
    val averageHeartrate: Float?,
    val maxHeartrate: Float?,
    val averageCadence: Float?,
    val lapIndex: Int,
    val split: Int,
)

data class Split(
    val distance: Float,
    val elapsedTime: Int,
    val movingTime: Int,
    val averageSpeed: Float,
    val averageHeartrate: Float?,
    val averageCadence: Float?,
    val averageGradeAdjustedSpeed: Float?,
    val paceZone: Int?,
    val splits: Int,
)

data class BestEffort(
    val id: Long,
    val name: String,
    val elapsedTime: Int,
    val movingTime: Int,
    val distance: Float,
    val startDate: ZonedDateTime,
    val startIndex: Int,
    val endIndex: Int,
    val isUserBestEffort: Boolean?,
)
